name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      env:
        TMP_WORK_DIR: "tmp_dir"
      run: |
        mkdir ${TMP_WORK_DIR}
        cd ${TMP_WORK_DIR}
        git clone https://github.com/eigenteam/eigen-git-mirror.git
        cd eigen-git-mirror
        git checkout 3.3.7
        cd ../../
        sudo mv ${TMP_WORK_DIR}/eigen-git-mirror /opt/
        sudo ln -s /opt/eigen-git-mirror/Eigen/ /usr/local/include/Eigen
        sudo ln -s /opt/eigen-git-mirror/unsupported/ /usr/local/include/unsupported
        cd ${TMP_WORK_DIR}
        git clone https://github.com/sKujirai/vtkmesh.git
        cd vtkmesh
        git checkout v1.0.0
        cd ../../
        sudo mkdir /opt/vtkmesh
        sudo mv ${TMP_WORK_DIR}/vtkmesh /opt/vtkmesh/
        rm -rf ${TMP_WORK_DIR}
    - name: make
      run: make
    - name: execute_debug
      run: ./pf_martensite_dev
    - name: execute_release
      run: ./pf_martensite_prod
